import {test} from 'node:test';import assert from 'node:assert/strict';
import {indexSeconds,evaluateDimensionalTravel,reconcileDimensionalTravel,requireCompleteDimensionalQ} from './dimensional-travel.mjs';
// Independent, explicitly TEST-ONLY declarations. These never become the production machine or rate.
const input={definition:{projectId:'test-only',version:'1',complete:true,features:[{id:'end',partId:'p1',units:'in',position:[16]}],requiredOperationIds:['cut'],sourcedItemsComplete:true},storeRevision:'a'.repeat(40),materials:[{storeSku:'TEST-STOCK',quantity:1,sellingPrice:4,priceSource:'TEST-ONLY',availability:'AVAILABLE'}],capability:{id:'TEST-ENVELOPE',version:'1',status:'SUPPORTABLE'},model:{id:'TEST-CYCLE',version:'1',basis:'DECLARED_FIXTURE',datums:{A:{declared:true},B:{declared:true}},referenceMethods:{stop:{id:'TEST-STOP',version:'1',basis:'DECLARED_FIXTURE',seconds:2}},index:{velocityInPerSec:2,accelerationInPerSec2:1},tools:{saw:{stationId:'TEST-SAW',approachSec:1,retractSec:1,cuttingFeedInPerMin:60}}},rate:{id:'TEST-RATE',version:'1',basis:'DECLARED_FIXTURE',units:'USD/hour',value:60},plan:{operations:[{id:'ref',kind:'REFERENCE',method:'stop'},{id:'move',kind:'INDEX',distanceIn:8,toolEngaged:false},{id:'cut',kind:'SAW',toolId:'saw',pathIn:2,passes:1,stopped:true,holdConfirmed:true,retractedAfter:true,requiredOperationIds:['cut']} ]}};
test('index trapezoid and triangle match independently calculated seconds',()=>{assert.equal(indexSeconds(8,2,1),6);assert.equal(indexSeconds(1,2,1),2);});
test('same evaluator produces both passes: 2+6+4 seconds, 20 cents service, $4.20 complete Q',()=>{const a=evaluateDimensionalTravel(input);assert.equal(a.T_MACHINE_seconds,12);assert.equal(a.machineServicePrice,.2);assert.equal(requireCompleteDimensionalQ(a),4.2);assert.deepEqual(reconcileDimensionalTravel(a,input).passB,a);});
test('project name cannot change economics',()=>{const other=structuredClone(input);other.definition.projectId='another-project';assert.equal(evaluateDimensionalTravel(other).Q,4.2);});
test('missing rate, invalid position, missing operation and tool/index overlap prohibit Q',()=>{
 const cases=[['STORE_MACHINE_SELL_RATE_REQUIRED',x=>x.rate=null],['POSITION_INVALID',x=>x.plan.operations.shift()],['REQUIRED_OPERATION_COVERAGE_REQUIRED',x=>x.plan.operations.pop()],['INDEX_WITH_TOOL_ENGAGED',x=>x.plan.operations[1].toolEngaged=true]];
 for(const [code,change] of cases){const x=structuredClone(input);change(x);const a=evaluateDimensionalTravel(x);assert.equal(a.Q,null);assert.ok(a.unresolved.includes(code));assert.throws(()=>requireCompleteDimensionalQ(a),/NO_COMPLETE_Q/);}
});
test('changed input requires new version; altered result is rejected',()=>{const a=evaluateDimensionalTravel(input);const x=structuredClone(input);x.materials[0].sellingPrice=5;assert.throws(()=>reconcileDimensionalTravel(a,x),/STORE_INPUT_CHANGED_NEW_VERSION_REQUIRED/);assert.throws(()=>reconcileDimensionalTravel({...a,resultIdentity:'changed'},input),/STORE_CALCULATION_DIVERGENCE/);assert.throws(()=>requireCompleteDimensionalQ({...a,Q:4}),/STORE_RESULT_CHANGED/);});
